on:
  workflow_dispatch:

jobs:
  build:
    uses: Itexoft/DevOpsKit/.github/workflows/autotools-multi-rid-build.yml@master
    with:
      project_name: samba
      apt_packages: libgnutls28-dev libpopt-dev python3 pkg-config
      brew_packages: gnutls popt python pkg-config
      msys2_packages: >
        mingw-w64-x86_64-gnutls mingw-w64-x86_64-popt
        mingw-w64-x86_64-python mingw-w64-x86_64-pkg-config
      pre_setup_script_linux: |
        pkg-config --version
      pre_setup_script_macos: |
        pkg-config --version
      pre_setup_script_windows: |
        pkg-config --version || true
      pre_configure_script: |
        autoreconf -i || true
      configure_args: |
        --enable-silent-rules
      configure_path: ../configure
      build_dir: build
      autoreconf: "false"
      checkout_submodules: "recursive"
      extra_env_linux: |
        CCACHE_DIR=/tmp/.ccache
      extra_env_macos: |
        CCACHE_DIR=/tmp/.ccache
      extra_env_windows: |
        CCACHE_DIR=/c/tmp/.ccache
    secrets: inherit
