---
'on':
  workflow_dispatch:

jobs:
  build:
    uses: >-
      Itexoft/DevOpsKit/.github/workflows/autotools-multi-rid-build.yml@master
    with:
      project_name: samba
      apt_packages: >
        libgnutls28-dev libpopt-dev python3 pkg-config
        libldap2-dev liblmdb-dev libgpgme11-dev
      brew_packages: gnutls popt python pkg-config openldap lmdb python-gpgme
      msys2_packages: >
        mingw-w64-x86_64-gnutls mingw-w64-x86_64-popt
        mingw-w64-x86_64-python mingw-w64-x86_64-pkg-config
        mingw-w64-x86_64-openldap mingw-w64-x86_64-lmdb
      pre_setup_script_linux: |
        pkg-config --version
      pre_setup_script_macos: |
        pkg-config --version
      pre_setup_script_windows: |
        pkg-config --version || true
      pre_configure_script: |
        autoreconf -i || true
      configure_path: ./configure
      build_dir: ""
      autoreconf: "false"
      checkout_submodules: "recursive"
      extra_env_linux: |
        CCACHE_DIR=/tmp/.ccache
      extra_env_macos: |
        CCACHE_DIR=/tmp/.ccache
      extra_env_windows: |
        CCACHE_DIR=/c/tmp/.ccache
    secrets: inherit
