name: smbcquotas-macos-monolith
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: macOS deps + build
        if: runner.os == 'macOS'
        run: |
          set -e
          brew update
          for f in gpgme libassuan libgpg-error gettext; do
            brew list "$f" >/dev/null 2>&1 || brew install "$f"
            if [ -n "$(brew outdated -q "$f")" ]; then brew upgrade "$f"; fi
          done
          for pkg in gpgmepy gnupg gnutls popt python pkg-config openldap lmdb jansson libtirpc flex bison cups libarchive dbus glib autoconf automake libtool git gdb perl cpanminus swig krb5 readline libxcrypt icu4c utf8proc cmocka openssl@3 python-markdown; do
            brew list "$pkg" >/dev/null 2>&1 || brew install "$pkg"
          done
          cpanm Parse::Yapp

          B=$(brew --prefix)
          GP=$(brew --prefix gpgme)
          AS=$(brew --prefix libassuan)
          GE=$(brew --prefix libgpg-error)
          GT=$(brew --prefix gettext)
          TI=$(brew --prefix libtirpc)
          AR=$(brew --prefix libarchive)
          KR=$(brew --prefix krb5)
          OL=$(brew --prefix openldap)
          CU=$(brew --prefix cups)
          GN=$(brew --prefix gnutls)
          RL=$(brew --prefix readline)
          LX=$(brew --prefix libxcrypt)
          IC=$(brew --prefix icu4c)
          U8=$(brew --prefix utf8proc)
          O3=$(brew --prefix openssl@3)
          FB=$(brew --prefix bison)
          FX=$(brew --prefix flex)

          export PATH="$B/opt/python@3.13/libexec/bin:$FB/bin:$FX/bin:$GP/bin:$B/bin:$PATH"
          export PKG_CONFIG_PATH="$IC/lib/pkgconfig:$U8/lib/pkgconfig:$GN/lib/pkgconfig:$GP/lib/pkgconfig:$AS/lib/pkgconfig:$GE/lib/pkgconfig:$TI/lib/pkgconfig:$AR/lib/pkgconfig:$KR/lib/pkgconfig:$OL/lib/pkgconfig:$CU/lib/pkgconfig:$O3/lib/pkgconfig:$B/lib/pkgconfig:$B/share/pkgconfig"
          export CPPFLAGS="-I$RL/include -I$GN/include -I$LX/include -I$IC/include -I$U8/include -I$O3/include -I$B/include -I$GP/include -I$AS/include -I$GE/include -I$GT/include -I$AR/include -I$KR/include -I$OL/include -I$CU/include -Wno-error=unused-command-line-argument -Qunused-arguments ${CPPFLAGS:-}"
          export LDFLAGS="-L$RL/lib -L$GN/lib -L$LX/lib -L$IC/lib -L$U8/lib -L$O3/lib -L$GP/lib -L$AS/lib -L$GE/lib -L$GT/lib -L$AR/lib -L$KR/lib -L$OL/lib -L$CU/lib ${LDFLAGS:-} -lcrypt -Wl,-rpath,@executable_path/lib"

          mkdir -p .ci
          printf '%s\n' '#ifndef HAVE_REALLOCARRAY' '#define reallocarray(p,nmemb,size) realloc_array((p),(size),(nmemb),0)' '#endif' > .ci/compat_darwin.h

          git checkout -- lib/ldb/wscript || true
          if ! grep -q "test_ldb_comparison_fold'.*enabled=False" lib/ldb/wscript; then
            sed -E -i '' "s/\('test_ldb_comparison_fold',/\('test_ldb_comparison_fold', enabled=False,/" lib/ldb/wscript
          fi

          cat > .ci/bison <<'EOF'
          #!/bin/sh
          REAL="$(brew --prefix bison)/bin/bison"
          args=""
          for a in "$@"; do
            [ "$a" = "--no-line" ] && a="--no-lines"
            args="$args \"$a\""
          done
          eval exec "$REAL" $args
          EOF
          chmod +x .ci/bison
          export PATH="$(pwd)/.ci:$PATH"

          $B/bin/python3 -m venv --system-site-packages .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install dnspython iso8601 pyasn1 setproctitle requests markdown cryptography

          PY="$(pwd)/.venv/bin/python"

          set +e
          CPPFLAGS="-include $(pwd)/.ci/compat_darwin.h $CPPFLAGS" CFLAGS="-include $(pwd)/.ci/compat_darwin.h ${CFLAGS:-}" \
          PKG_CONFIG_PATH="$PKG_CONFIG_PATH" LDFLAGS="$LDFLAGS" PYTHON="$PY" \
          ./configure --without-acl-support --without-gettext --bundled-libraries=ALL \
            --nonshared-binary=smbcquotas \
            --with-static-modules=vfs_fruit,vfs_streams_xattr,vfs_catia,vfs_acl_xattr,vfs_acl_tdb,vfs_xattr_tdb,vfs_recycle,vfs_shadow_copy2,vfs_full_audit,vfs_extd_audit,vfs_readahead,vfs_preopen,vfs_aio_pthread,vfs_fake_perms,vfs_readonly,vfs_offline,vfs_time_audit,vfs_commit,vfs_crossrename,vfs_dirsort,vfs_expand_msdfs,vfs_default_quota,vfs_streams_depot,vfs_syncops,vfs_widelinks,vfs_worm,vfs_audit,auth_unix,auth_winbind,auth_builtin,pdb_tdbsam,pdb_smbpasswd,pdb_ldapsam \
            --with-shared-modules=idmap_tdb,idmap_tdb2,idmap_rid,idmap_autorid,idmap_ad,idmap_ldap,idmap_script,idmap_nss,idmap_rfc2307,pdb_wbc_sam \
            --without-gpgme
          st=$?
          set -e
          if [ "$st" -ne 0 ]; then
            echo "----- HEAD bin/config.log (first 200) -----" || true
            [ -f bin/config.log ] && sed -n '1,200p' bin/config.log || true
            echo "----- TAIL bin/config.log (last 400) -----" || true
            [ -f bin/config.log ] && tail -n 400 bin/config.log || true
            exit "$st"
          fi

          CFLAGS="$CFLAGS -include $(pwd)/.ci/compat_darwin.h" \
          CPPFLAGS="$CPPFLAGS -include $(pwd)/.ci/compat_darwin.h" \
          make JOBS="$(sysctl -n hw.ncpu)"

      - name: Bundle dylibs
        if: runner.os == 'macOS'
        run: |
          set -euo pipefail
          B=$(brew --prefix)
          mkdir -p out out/lib
          : > out/lib/.origmap
          cp bin/smbcquotas out/smbcquotas

          deps_list() { otool -L "$1" | awk '/^\t/ {print $1}' | grep -Ev '^(/usr/lib|/System/Library)'; }
          map_add() { echo "$1|$2" >> out/lib/.origmap; }
          map_get() { awk -F'|' -v k="$1" '$1==k{print $2;exit}' out/lib/.origmap; }
          resolve_dep() {
            ref="$1"; dep="$2"
            case "$dep" in
              @loader_path/*) echo "$(dirname "$ref")/${dep#@loader_path/}"; return 0 ;;
              @rpath/*)
                for r in $(otool -l "$ref" | awk '/LC_RPATH/{getline; print $2}'); do
                  case "$r" in
                    @loader_path/*) d="$(dirname "$ref")/${r#@loader_path/}" ;;
                    @executable_path/*) d="$(pwd)/out/${r#@executable_path/}" ;;
                    /*) d="$r" ;;
                    *) d="" ;;
                  esac
                  [ -n "$d" ] && [ -f "$d/${dep#@rpath/}" ] && { echo "$d/${dep#@rpath/}"; return 0; }
                done
                ;;
              /*) echo "$dep"; return 0 ;;
            esac
            n="$(basename "$dep")"
            for p in "$B"/opt/*/lib "$B"/lib; do
              [ -f "$p/$n" ] && { echo "$p/$n"; return 0; }
            done
            return 1
          }

          initial="$(deps_list out/smbcquotas || true)"
          queue=""
          for dep in $initial; do
            abs="$(resolve_dep out/smbcquotas "$dep")" || continue
            base="$(basename "$abs")"
            if [ ! -f "out/lib/$base" ]; then
              cp -pRL "$abs" "out/lib/$base"
              install_name_tool -id "@rpath/$base" "out/lib/$base" || true
              map_add "$base" "$abs"
              queue="$queue $base"
            fi
          done

          while [ -n "$queue" ]; do
            next=""
            for b in $queue; do
              orig="$(map_get "$b")"
              for sub in $(deps_list "$orig" || true); do
                sabs="$(resolve_dep "$orig" "$sub")" || continue
                sbase="$(basename "$sabs")"
                if [ ! -f "out/lib/$sbase" ]; then
                  cp -pRL "$sabs" "out/lib/$sbase"
                  install_name_tool -id "@rpath/$sbase" "out/lib/$sbase" || true
                  map_add "$sbase" "$sabs"
                  next="$next $sbase"
                fi
                install_name_tool -change "$sabs" "@rpath/$sbase" "out/lib/$b" || true
              done
            done
            queue="$(printf '%s\n' $next | tr ' ' '\n' | awk 'NF' | sort -u | tr '\n' ' ')"
          done

          for dep in $initial; do
            abs="$(resolve_dep out/smbcquotas "$dep")" || continue
            base="$(basename "$abs")"
            install_name_tool -change "$abs" "@rpath/$base" out/smbcquotas || true
          done
          install_name_tool -add_rpath "@executable_path/lib" out/smbcquotas || true

          /usr/bin/codesign --force -s - --timestamp=none out/smbcquotas
          find out/lib -type f -name '*.dylib' -print0 | xargs -0 -I{} /usr/bin/codesign --force -s - --timestamp=none {}
          /usr/bin/codesign --verify --deep --strict out/smbcquotas

          if otool -L out/smbcquotas | grep -q '/opt/homebrew'; then
            otool -L out/smbcquotas
            exit 1
          fi
          otool -L out/smbcquotas

      - name: Archive artifacts
        if: runner.os == 'macOS'
        run: |
          set -e
          find bin -type f -perm -111 -not -name smbcquotas -print0 | xargs -0 -I{} cp {} out/ || true
          tar -czf smbcquotas-macos-monolith.tar.gz -C out .

      - name: Upload config logs (always)
        if: always() && runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: samba-config-logs
          path: |
            bin/config.log
          if-no-files-found: warn

      - uses: actions/upload-artifact@v4
        if: runner.os == 'macOS'
        with:
          name: smbcquotas-macos-monolith
          path: smbcquotas-macos-monolith.tar.gz
          if-no-files-found: error